grid-columns: 2
horizontal-gap: 240

robot: dogzillad {
  grid-rows: 4
  grid-columns: 1
  vertical-gap: 0

  qml: QML daemon {
    style.fill: "#3bd23d"
  }
  qtros: Qt ROS2\ngenerated modules {
    style.fill: "#3bd23d"
  }
  rmw: ROS MiddleWare (RMW) {
  }
  fastdds: "" {
    shape: image
    icon: Fast-DDS-Logo-horizontal-no-margin.png
    height: 60
  }
}

digitwin: Digital Twin {
  grid-rows: 6
  grid-columns: 1
  vertical-gap: 0

  qml: QML scene {
    style.fill: "#3bd23d"
  }
  qq3d: Qt Quick 3D {
    style.fill: "#3bd23d"
  }
  qtros: Qt ROS2\ngenerated modules {
    style.fill: "#3bd23d"
  }
  rmw: ROS MiddleWare (RMW) {
  }
  fastdds: "" {
    shape: image
    icon: Fast-DDS-Logo-horizontal-no-margin.png
    width: 60
    height: 60
  }
  bottom-spacer: "" {
    style.opacity: 0
    width: 1
    height: 30
  }
}

robot.fastdds <-> digitwin.fastdds: DDS pub/sub topics {
  style: {
    font-size: 20
  }
}
