// Generated by urdf2quick3dexporter.py from 'dogzilla.urdf'

import QtQuick
import QtQuick3D
import QtQuick3D.Helpers
import Dogzilla
import "links"
import "materials"

Node {
    id: rootNode

    required property DogzillaControl control
    property real sceneUnitsPerMeter: 100.0
    property real instanceScale: 10.0
    scale: Qt.vector3d(instanceScale, instanceScale, instanceScale)


    readonly property alias baseFootprintPosition: base_footprint.scenePosition
    readonly property alias baseLinkPosition: base_link.scenePosition
    readonly property alias lfHipLinkPosition: lf_hip_link.scenePosition
    readonly property alias lfUpperLegLinkPosition: lf_upper_leg_link.scenePosition
    readonly property alias lfLowerLegLinkPosition: lf_lower_leg_link.scenePosition
    readonly property alias rfHipLinkPosition: rf_hip_link.scenePosition
    readonly property alias rfUpperLegLinkPosition: rf_upper_leg_link.scenePosition
    readonly property alias rfLowerLegLinkPosition: rf_lower_leg_link.scenePosition
    readonly property alias lhHipLinkPosition: lh_hip_link.scenePosition
    readonly property alias lhUpperLegLinkPosition: lh_upper_leg_link.scenePosition
    readonly property alias lhLowerLegLinkPosition: lh_lower_leg_link.scenePosition
    readonly property alias rhHipLinkPosition: rh_hip_link.scenePosition
    readonly property alias rhUpperLegLinkPosition: rh_upper_leg_link.scenePosition
    readonly property alias rhLowerLegLinkPosition: rh_lower_leg_link.scenePosition
    readonly property alias cameraLinkPosition: camera_link.scenePosition
    readonly property alias laserLinkPosition: laser_link.scenePosition
    readonly property alias imuLinkPosition: imu_link.scenePosition

    // Convert to Y-up
    rotation: Qt.quaternion(0.50000000, -0.50000000, -0.50000000, -0.50000000)

    Node {
        Node {
            id: base_footprint
        }
        Node {
            id: base_joint
            position: Qt.vector3d(0.0, 0.0, 1.0)
            BaseLink {
                id: base_link
                scale: Qt.vector3d(100.0, 100.0, 100.0)
            }
            Node {
                id: lf_hip_joint
                position: Qt.vector3d(9.332, 2.2407, 1.454)
                Node {
                    id: lf_hip_jointPivot
                    readonly property vector3d axis: Qt.vector3d(1.0, 0.0, 0.0)
                    rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.lfHipJointAngle)
                    LfHipLink {
                        id: lf_hip_link
                        scale: Qt.vector3d(100.0, 100.0, 100.0)
                    }
                    Node {
                        id: lf_upper_leg_joint
                        position: Qt.vector3d(-1.8325, 4.9313, 0.0)
                        Node {
                            id: lf_upper_leg_jointPivot
                            readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                            rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.lfUpperLegJointAngle)
                            LfUpperLegLink {
                                id: lf_upper_leg_link
                                scale: Qt.vector3d(100.0, 100.0, 100.0)
                            }
                            Node {
                                id: lf_lower_leg_joint
                                position: Qt.vector3d(0.0, -0.072, -5.9896)
                                Node {
                                    id: lf_lower_leg_jointPivot
                                    readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                                    rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.lfLowerLegJointAngle)
                                    LfLowerLegLink {
                                        id: lf_lower_leg_link
                                        scale: Qt.vector3d(100.0, 100.0, 100.0)
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Node {
                id: rf_hip_joint
                position: Qt.vector3d(9.332, -2.2517, 1.454)
                Node {
                    id: rf_hip_jointPivot
                    readonly property vector3d axis: Qt.vector3d(-1.0, 0.0, 0.0)
                    rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.rfHipJointAngle)
                    RfHipLink {
                        id: rf_hip_link
                        scale: Qt.vector3d(100.0, 100.0, 100.0)
                    }
                    Node {
                        id: rf_upper_leg_joint
                        position: Qt.vector3d(-1.8325, -4.9313, 0.0)
                        Node {
                            id: rf_upper_leg_jointPivot
                            readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                            rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.rfUpperLegJointAngle)
                            RfUpperLegLink {
                                id: rf_upper_leg_link
                                scale: Qt.vector3d(100.0, 100.0, 100.0)
                            }
                            Node {
                                id: rf_lower_leg_joint
                                position: Qt.vector3d(0.0, 0.0, -5.9896)
                                Node {
                                    id: rf_lower_leg_jointPivot
                                    readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                                    rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.rfLowerLegJointAngle)
                                    RfLowerLegLink {
                                        id: rf_lower_leg_link
                                        scale: Qt.vector3d(100.0, 100.0, 100.0)
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Node {
                id: lh_hip_joint
                position: Qt.vector3d(-5.668, 2.2407, 1.454)
                Node {
                    id: lh_hip_jointPivot
                    readonly property vector3d axis: Qt.vector3d(1.0, 0.0, 0.0)
                    rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.lhHipJointAngle)
                    LhHipLink {
                        id: lh_hip_link
                        scale: Qt.vector3d(100.0, 100.0, 100.0)
                    }
                    Node {
                        id: lh_upper_leg_joint
                        position: Qt.vector3d(-1.8325, 4.931305, 0.0)
                        Node {
                            id: lh_upper_leg_jointPivot
                            readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                            rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.lhUpperLegJointAngle)
                            LhUpperLegLink {
                                id: lh_upper_leg_link
                                scale: Qt.vector3d(100.0, 100.0, 100.0)
                            }
                            Node {
                                id: lh_lower_leg_joint
                                position: Qt.vector3d(0.0, -0.072, -5.9896)
                                Node {
                                    id: lh_lower_leg_jointPivot
                                    readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                                    rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.lhLowerLegJointAngle)
                                    LhLowerLegLink {
                                        id: lh_lower_leg_link
                                        scale: Qt.vector3d(100.0, 100.0, 100.0)
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Node {
                id: rh_hip_joint
                position: Qt.vector3d(-5.668, -2.2517, 1.454)
                Node {
                    id: rh_hip_jointPivot
                    readonly property vector3d axis: Qt.vector3d(-1.0, 0.0, 0.0)
                    rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.rhHipJointAngle)
                    RhHipLink {
                        id: rh_hip_link
                        scale: Qt.vector3d(100.0, 100.0, 100.0)
                    }
                    Node {
                        id: rh_upper_leg_joint
                        position: Qt.vector3d(-1.8325, -4.9313, 0.0)
                        Node {
                            id: rh_upper_leg_jointPivot
                            readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                            rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.rhUpperLegJointAngle)
                            RhUpperLegLink {
                                id: rh_upper_leg_link
                                scale: Qt.vector3d(100.0, 100.0, 100.0)
                            }
                            Node {
                                id: rh_lower_leg_joint
                                position: Qt.vector3d(0.0, 0.0, -5.9896)
                                Node {
                                    id: rh_lower_leg_jointPivot
                                    readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                                    rotation: Quaternion.fromAxisAndAngle(axis, rootNode.control.rhLowerLegJointAngle)
                                    RhLowerLegLink {
                                        id: rh_lower_leg_link
                                        scale: Qt.vector3d(100.0, 100.0, 100.0)
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Node {
                id: camera_joint
                position: Qt.vector3d(7.5751, 0.0, 5.9653)
                CameraLink {
                    id: camera_link
                    scale: Qt.vector3d(100.0, 100.0, 100.0)
                }
            }
            Node {
                id: laser_joint
                position: Qt.vector3d(-1.6732, 0.004416, 10.335)
                LaserLink {
                    id: laser_link
                    scale: Qt.vector3d(100.0, 100.0, 100.0)
                }
            }
            Node {
                id: imu_joint
                position: Qt.vector3d(8.5, 0.004416, 7.0)
                Model {
                    id: imu_link
                    position: Qt.vector3d(0.0, 0.0, -4.0)
                    source: "#Cube"
                    scale: Qt.vector3d(0.02, 0.02, 0.001)
                    materials: GreenPCB { }
                }
            }
        }
    }
}
