// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/dogzilla-digitwin/dogzilla/urdf/dogzilla.urdf' on 2026-03-24T19:26:43.953593 | License: see LICENSE
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick3D
import QtQuick3D.Helpers
import QtRos2.Core as Ros2
import QtRos2.GeometryMsgs as GeomMsgs
import QtRos2.SensorMsgs as SensorMsgs
import QtRos2.StdSrvs as StdSrvs
import Dogzilla
import Dogzilla.Interfaces

Item {
    id: root
    implicitWidth: 1920
    implicitHeight: 1080

    View3D {
        id: view3D
        anchors.fill: parent

        camera: sceneCamera
        environment: sceneEnvironment

        SceneEnvironment {
            id: sceneEnvironment
            clearColor: "#222"
            backgroundMode: SceneEnvironment.Color
            antialiasingMode: SceneEnvironment.MSAA
            antialiasingQuality: SceneEnvironment.High
        }

        Node {
            id: cameraNode
            eulerRotation: Qt.vector3d(-10, 150, 0)
            PerspectiveCamera {
                id: sceneCamera
                z: 1000
                property real stickDistance: 300
                property real halfV: stickDistance * Math.tan(sceneCamera.fieldOfView / 2 * Math.PI / 180)
                property real halfH: halfV * (view3D.width / view3D.height)

                Node {
                    id: rightStick
                    x: ((rightStickControl.x + rightStickControl.width  / 2) / view3D.width  - 0.5) * 2 * sceneCamera.halfH
                    y: (0.5 - (rightStickControl.y + rightStickControl.height / 2) / view3D.height) * 2 * sceneCamera.halfV
                    z: -sceneCamera.stickDistance
                    // Perspective compensation: rotate to face the camera eye at the origin
                    eulerRotation.y: -Math.atan2(x, sceneCamera.stickDistance) * 180 / Math.PI
                    eulerRotation.x: Math.atan2(y, sceneCamera.stickDistance) * 180 / Math.PI
                    ThumbStick {
                        axes: rightStickControl.axes
                    }
                }

                Node {
                    id: leftStick
                    x: ((leftStickControl.x + leftStickControl.width  / 2) / view3D.width  - 0.5) * 2 * sceneCamera.halfH
                    y: (0.5 - (leftStickControl.y + leftStickControl.height / 2) / view3D.height) * 2 * sceneCamera.halfV
                    z: -sceneCamera.stickDistance
                    // Perspective compensation: rotate to face the camera eye at the origin
                    eulerRotation.y: -Math.atan2(x, sceneCamera.stickDistance) * 180 / Math.PI
                    eulerRotation.x: Math.atan2(y, sceneCamera.stickDistance) * 180 / Math.PI
                    ThumbStick {
                        axes: leftStickControl.axes
                    }
                }
            }

            DirectionalLight {
                id: directionalLight
                eulerRotation: Qt.vector3d(-30, 30, 0)
            }
        }

        OrbitCameraController {
            origin: cameraNode
            camera: sceneCamera
        }

        Node {
            id: cameraViewScreen
            eulerRotation: Qt.vector3d(180, 0, 180)
            x: dogsEyeView.width / 2         // center on axis
            y: dogsEyeView.height / 2 + 100  // center on line of sight
            z: 1000                          // in front of the dog; TODO calibrate?
            Image {
                id: dogsEyeView
                width: 1920
                height: 1080
                cache: false
                source: "image://camera/" + ReceivedImageProvider.currentFrame

                Text {
                    anchors {
                        horizontalCenter: parent.horizontalCenter
                        bottom: parent.bottom
                        margins: 6
                    }
                    color: "white"
                    text: cameraNode.eulerRotation.x.toFixed(2) + ", " +
                          cameraNode.eulerRotation.y.toFixed(2) + ", " +
                          cameraNode.eulerRotation.z.toFixed(2)
                }
            }
        }

        Node {
            id: lidarRepresentation
            y: 100
            Model {
                scale: Qt.vector3d(0.1, 0.1, 0.01)
                source: "#Cube"
                instancing: LidarInstanceTable {
                    ranges: laserSub.ranges
                    intensities: laserSub.intensities
                    angleIncrement: laserSub.angleIncrement
                }
                materials: [
                    PrincipledMaterial {
                        alphaMode: PrincipledMaterial.Opaque
                        cullMode: PrincipledMaterial.NoCulling
                        emissiveFactor: Qt.vector3d(0.1, 0.1, 0.1)
                    }
                ]
            }
        }

        Dogzilla {
            id: robotRoot
            // toQuaternion() yields a QtQuick3D-frame orientation (the bridge's
            // Quaternion uses Qt's axis convention), so apply the body orientation in
            // *scene* space — outside the model's Z-up→Y-up conversion (R_conv):
            // bodyOrientation ∘ R_conv. (R_conv ∘ q would act in the model's Z-up frame
            // and a pitch would read as a roll.) yUp must match Dogzilla.qml's root
            // "Convert to Y-up" rotation.
            readonly property quaternion yUp: Qt.quaternion(0.5, -0.5, -0.5, -0.5)
            rotation: poseSubscriber.pose.orientation.toQuaternion().times(yUp)
            control: DogzillaControl {
                id: ctl
            }
        }
        AxisHelper {
            y: -115
            scale: Qt.vector3d(0.2, 0.2, 0.2)
        }
    }

    // Named-motion store (persisted JSON); shared with the teach panel and
    // published to the robot by rosNode.publishLibrary().
    MotionLibrary {
        id: motionLib
        onChanged: rosNode.publishLibrary()
    }

    Ros2.Node {
        id: rosNode
        nodeName: "digitwin"
        // The robot's namespace: all of its topics live under it, and its
        // daemon node is ${robotNamespace}/dogzillad. Kept separate from
        // this node's own name so `ros2 node list` reads honestly
        // (/digitwin vs /dogzilla/dogzillad).
        readonly property string robotNamespace: "/dogzilla"

        SensorMsgs.BatteryStateSubscriber {
            id: batterySub
            topic: `${rosNode.robotNamespace}/battery_state`
        }

        SensorMsgs.TemperatureSubscriber {
            id: tempSub
            topic: `${rosNode.robotNamespace}/telemetry/temperature`
            onTemperatureChanged: {
                panel.addTemperatureSample(
                    tempSub.header.stamp.sec + tempSub.header.stamp.nanosec / 1e9,
                    tempSub.temperature)
            }
        }

        StampedTelemetrySubscriber {
            id: teleSub
            topic: `${rosNode.robotNamespace}/telemetry/system`
            onMessageReceived: (msg) => {
                panel.addTelemetrySample(
                    teleSub.header.stamp.sec + teleSub.header.stamp.nanosec / 1e9,
                    teleSub.cpuPercent, teleSub.fanLevel)
            }
        }

        // Robot audio mixer: each channel is a parameter of the robot's
        // node -- one RemoteParameter per slider. `value` is desired state
        // (coalesced latest-wins, applied when the robot appears),
        // `reported` is what the robot actually holds (initial get +
        // /parameter_events). autoApply stays off until the slider has a
        // real starting point (see ControlPanel's `live`); out-of-range
        // values are rejected by the robot's declared bounds.
        Ros2.RemoteParameter {
            id: masterParam
            remoteNode: `${rosNode.robotNamespace}/dogzillad`
            name: "audio.master"
            autoApply: panel.masterVolumeLive
            value: panel.desiredMasterVolume
        }
        Ros2.RemoteParameter {
            id: micParam
            remoteNode: `${rosNode.robotNamespace}/dogzillad`
            name: "audio.mic"
            autoApply: panel.micVolumeLive
            value: panel.desiredMicVolume
        }

        // Engage/disengage the legs via the robot's motors.engaged parameter.
        // `reported` is the robot's actual state (so the switch tracks the joystick too);
        // autoApply becomes true only when the user toggles the Switch
        // so a fresh twin never disengages the dog on connect.
        // property bool motorsDesired: false
        // property bool motorsTouched: false
        Ros2.RemoteParameter {
            id: engageParam
            remoteNode: `${rosNode.robotNamespace}/dogzillad`
            name: "motors.engaged"
            autoApply: false
            value: panel.motorsEngaged
        }

        // TODO stop using the deprecated single-value pub/sub types
        BoolPublisher {
            id: listenPublisher
            topic: `${rosNode.robotNamespace}/speech/listen`
        }

        StringSubscriber {
            id: speechStateSub
            topic: `${rosNode.robotNamespace}/speech/state`
            onMessageChanged: ptt.state = message
        }

        ChatMessageSubscriber {
            id: msgSub
            topic: `${rosNode.robotNamespace}/speech/log`
            onMessageReceived: (msg) => panel.addChatMessage(msg)
        }

        // The dog's voice: "Speak" sends a verbatim goal (use_llm=false), "Send"
        // an LLM goal (use_llm=true). Replaces the fire-and-forget /speech/say
        // and /speech/respond topics. Stopping is NOT a goal cancel -- see
        // stopSpeech below -- so the stop button also silences the robot's
        // autonomous STT->LLM voice, which has no goal here to cancel.
        SpeakActionClient {
            id: speakAction
            topic: `${rosNode.robotNamespace}/speech/speak`
        }

        // The stop button's "shut up now": silences TTS on the robot however the
        // speech started (twin goal or autonomous). std_srvs/Trigger for an ack.
        StdSrvs.TriggerServiceClient {
            id: stopSpeech
            topic: `${rosNode.robotNamespace}/speech/stop`
        }

        SensorMsgs.JointStateSubscriber {
            id: jointStateSubscriber
            topic: `${rosNode.robotNamespace}/joint_states`
            qos.queueSize: 1
            qos.reliability: Ros2.QualityOfService.ReliabilityBestEffort
            qos.history: Ros2.QualityOfService.HistoryKeepLast

            onMessageReceived: function (msg) {
                // console.log("JointStateSubscriber got", msg.name, msg.position, JSON.stringify(msg))
                robotRoot.control.updateJointState(msg.name, msg.position);
            }
        }

        GeomMsgs.PoseStampedSubscriber {
            id: poseSubscriber
            topic: `${rosNode.robotNamespace}/body_pose/state` // modern style for command/state topic separation
            onMessageReceived: function (msg) {
                console.log(JSON.stringify(msg))
            }
        }

        SensorMsgs.CompressedImageSubscriber {
            id: imageSubscriber
            topic: `${rosNode.robotNamespace}/camera/image/compressed`
            // Match the publisher's best-effort: tolerate dropped frames over Wi-Fi.
            qos: Ros2.QualityOfService.sensorData()
            onMessageReceived: function(msg) {
                // console.log(JSON.stringify(msg))
                // const QImage &im, int frame, int sec, int nsec
                ReceivedImageProvider.setImage(msg.image, msg.header.frameId,
                                               msg.header.stamp.sec, msg.header.stamp.nanosec)
            }
        }

        SensorMsgs.LaserScanSubscriber {
            id: laserSub
            topic: `${rosNode.robotNamespace}/sensor_msgs/msg/LaserScan`
            // Remote viewer: request best-effort. The publisher stays reliable
            // (onboard SLAM needs it), and reliable-offered satisfies this.
            qos: Ros2.QualityOfService.sensorData()
        }

        // step sideways
        property real strafeSpeed: rightStickControl.axes.x * -50
        // look up/down: change lidar and camera angle
        // The firmware pitch range is ±15° (ATTITUDE_LIMIT); full stick maps to it.
        // Stay well under 90° regardless, to avoid Euler gimbal lock (which would
        // make the other angles non-zero in the published quaternion).
        property real pitch: rightStickControl.axes.y * 15
        // yaw by stepping
        property real turnSpeed: leftStickControl.axes.x * -100
        // walk forwards or backwards
        property real walkSpeed: leftStickControl.axes.y * 100

        GeomMsgs.TwistPublisher {
            id: cmdVel
            topic: `${rosNode.robotNamespace}/cmd_vel` // legacy ROS1-style command topic, still in use
            linear: Qt.vector3d(rosNode.walkSpeed, rosNode.strafeSpeed, 0)
            angular: Qt.vector3d(0, 0, rosNode.turnSpeed)
        }

        GeomMsgs.PoseStampedPublisher {
            topic: `${rosNode.robotNamespace}/body_pose/command` // modern style for command/state topic separation
            header.frameId: "base_link" // name of link (main body part) as declared in dogzilla.urdf
            pose.orientation: GeomMsgs.Quaternion.fromEulerAngles(0, rosNode.pitch, 0)
        }

        // ---- Teach pendant plumbing ------------------------------------------
        // Plays a taught JointTrajectory; feedback drives the panel's progress.
        PlayMotionActionClient {
            id: motionAction
            topic: `${rosNode.robotNamespace}/motion/play`
        }
        property bool motionPlaying: false
        // Fraction 0..1 through the motion (the panel maps this to a highlighted
        // row; point count != waypoint count once holds add duplicate points).
        readonly property real motionProgress:
            (motionPlaying && motionAction.feedback) ? motionAction.feedback.progress : 0

        // "lfLowerLegJointAngle" (twin, degrees) -> "lf_lower_leg_joint" (ROS).
        function rosJointName(camel) {
            return camel.replace(/Angle$/, "").replace(/([A-Z])/g, "_$1").toLowerCase();
        }

        // Convert panel waypoints [{pose:{camelName:deg}, move, hold}] to a ROS
        // JointTrajectory (snake joint_names, radians). time_from_start is each
        // point's ARRIVAL time: waypoint k arrives after `move` seconds (the robot
        // interpolates to it over that span), and a non-zero `hold` adds a second,
        // identical point `hold` seconds later so the robot dwells there.
        function buildTrajectory(wps) {
            const order = robotRoot.control.jointInfos.map(j => j.name); // 12 camel names
            const names = order.map(rosJointName);
            const dur = (sec) => ({ sec: Math.floor(sec), nanosec: Math.round((sec % 1) * 1e9) });
            let points = [];
            let t = 0;
            for (let k = 0; k < wps.length; ++k) {
                const positions = order.map(cn => (wps[k].pose[cn] || 0) * Math.PI / 180);
                const move = wps[k].move ?? wps[k].duration ?? 1.0;   // back-compat: old `duration`
                const hold = wps[k].hold ?? 0;
                t += move;
                points.push({ positions: positions, timeFromStart: dur(t) });   // arrive
                if (hold > 0) {
                    t += hold;
                    points.push({ positions: positions, timeFromStart: dur(t) }); // hold
                }
            }
            return { jointNames: names, points: points };
        }

        function playMotion(wps) {
            if (!wps || wps.length === 0)
                return;
            rosNode.motionPlaying = true;
            motionAction.sendGoal({ trajectory: buildTrajectory(wps), name: "teach" })
                .then(() => rosNode.motionPlaying = false)
                .catch((e) => { console.warn("playMotion:", e); rosNode.motionPlaying = false; });
        }

        // Publish the whole named-motion library to the robot as { name: trajectory }
        // so it can play a spoken pose locally. Latched (transient-local) so a robot
        // that connects later still gets the current set. Called on any library edit.
        StringPublisher {
            id: libraryPub
            topic: `${rosNode.robotNamespace}/motion/library`
            qos: Ros2.QualityOfService.transientLocal()
        }
        function publishLibrary() {
            let lib = {};
            for (const name of motionLib.names) {
                try {
                    lib[name] = buildTrajectory(JSON.parse(motionLib.load(name)));
                } catch (e) {
                    console.warn("publishLibrary: skipping", name, e);
                }
            }
            // Assign the data property (not publish(value)): this stores the
            // state so the transient_local publisher replays it on connect for
            // subscribers that join after this early (Component.onCompleted)
            // call, before the rcl publisher even exists.
            libraryPub.data = JSON.stringify(lib);
        }
        Component.onCompleted: rosNode.publishLibrary()
    }

    ColumnLayout {
        anchors.right: parent.right
        anchors.top: parent.top
        anchors.bottom: parent.bottom
        anchors.margins: 12
        anchors.bottomMargin: 170
        width: Math.min(420, Math.max(280, parent.width * 0.28))
        TabBar {
            id: tabBar
            TabButton { text: "Control"; width: 100 }
            TabButton { text: "Teach"; width: 100 }
        }
        StackLayout {
            Layout.fillHeight: true
            Layout.fillWidth: true
            currentIndex: tabBar.currentIndex
            ControlPanel {
                id: panel
                targetRobot: robotRoot
                batteryLevel: batterySub.percentage
                motorsEngaged: engageParam.reported ?? false
                onMotorsEngagedChanged: engageParam.autoApply = true
                robotMasterVolume: masterParam.reported ?? 0
                robotMicVolume: micParam.reported ?? 0

                onStopSpeaking: stopSpeech.callService().catch(e => console.warn("stop:", e))
                onSpeakText: (t) => speakAction.sendGoal({ "text": t, "useLlm": false }).catch(e => console.warn("speak:", e))
                onSendText: (t) => speakAction.sendGoal({ "text": t, "useLlm": true }).catch(e => console.warn("speak:", e))
            }

            TeachPanel {
                id: teachPanel
                Layout.alignment: Qt.AlignTop
                Layout.preferredHeight: panel.height
                targetRobot: robotRoot
                library: motionLib
                engaged: engageParam.reported ?? false
                playing: rosNode.motionPlaying
                progress: rosNode.motionProgress

                onStop: motionAction.cancelGoal()
                onPlay: (wps) => rosNode.playMotion(wps)
            }
        }
    }

    RowLayout {
        spacing: 30
        anchors {
            bottom: parent.bottom
            right: parent.right
            rightMargin: 160
            bottomMargin: 40
        }

        Rectangle {
            id: ptt
            width: 60
            height: width
            radius: 6
            border.color: pttH.pressed ? "cyan" : "black"
            border.width: 1
            property color readyColor: "grey"
            gradient: Gradient {
                GradientStop { position: pttH.pressed ? 1 : 0; color: "lightgreen" }
                GradientStop { position: pttH.pressed ? 0 : 1; color: ptt.readyColor }
            }

            states: [
                State {
                    name: "idle"
                    PropertyChanges { target: ptt; readyColor: "grey" }
                },
                State {
                    name: "prep" // ROS message overhead + turning the fan off
                    PropertyChanges { target: ptt; readyColor: "yellow" }
                },
                State {
                    name: "listening"
                    PropertyChanges { target: ptt; readyColor: "red" }
                },
                State {
                    name: "transcribing"
                    PropertyChanges { target: ptt; readyColor: "blue" }
                }
            ]
            state: "idle"
            transitions: [
                Transition {
                    to: "prep"
                    // Ramp readyColor grey -> red (prep's value) over ~1s while held, so
                    // the gradient "charges up" as the fan spins down before listening.
                    // from/to are taken automatically from the idle/prep readyColor values.
                    ColorAnimation { target: ptt; property: "readyColor"; duration: 500 }
                }
            ]

            TapHandler {
                id: pttH
                onPressedChanged: {
                    listenPublisher.publish(pttH.pressed)
                    if (pttH.pressed)
                        ptt.state = "prep"
                }
            }
            Text {
                text: "Press to\nTalk"
                anchors.centerIn: parent
                horizontalAlignment: Text.AlignHCenter
            }

            Text {
                anchors.bottom: parent.top
                anchors.margins: 3
                width: parent.width
                horizontalAlignment: Text.AlignHCenter
                text: ptt.state
                color: "white"
            }
        }

        /*
        Image {
            source: "images/stop.svg"
            sourceSize: Qt.size(60, 60)
            rotation: stopTH.pressed ? 45 : 0
            TapHandler {
                id: stopTH
                // onTapped: TODO
            }
        }
        */
    }

    ThumbStickControl {
        id: rightStickControl
        width: parent.width / 7
        anchors {
            bottom: parent.bottom
            right: parent.right
        }
        Text {
            anchors {
                right: parent.right
                bottom: parent.bottom
                margins: 6
            }
            color: "white"
            text: `${rightStickControl.axes.x.toFixed(2)} ${rightStickControl.axes.y.toFixed(2)}` +
                  ` strafe ${rosNode.strafeSpeed.toFixed(2)} pitch ${rosNode.pitch.toFixed(2)}`
        }
    }

    ThumbStickControl {
        id: leftStickControl
        width: parent.width / 6
        anchors {
            bottom: parent.bottom
            left: parent.left
        }
        Text {
            anchors {
                left: parent.left
                bottom: parent.bottom
                margins: 6
            }
            color: "white"
            text: `${leftStickControl.axes.x.toFixed(2)} ${leftStickControl.axes.y.toFixed(2)}` +
                  ` turn ${rosNode.turnSpeed.toFixed(2)} walk ${rosNode.walkSpeed.toFixed(2)}`
        }
    }
}
