// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/qtros/examples/robotarmcollision/simple_arm.urdf' on 2026-09-18T11:29:23.470640
import QtQuick

QtObject {
    // Toggles the generated DynamicRigidBody.isKinematic; bound from the model.
    // true: links are driven by joint transforms; false: simulated by the PhysicsWorld.
    property bool isKinematic: true
    // When true, each generated DynamicRigidBody emits trigger reports so a
    // TriggerBody can detect the robot overlapping it. Default false (off).
    property bool sendTriggerReports: false
    property real elbowFlexAngle: 0
    property real shoulderLiftAngle: 0
    property real shoulderPanAngle: 0
    readonly property list<variant> jointInfos: [
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -1.5708,
            "name": "elbowFlexAngle",
            "type": "revolute",
            "upper": 1.5708
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -1.5708,
            "name": "shoulderLiftAngle",
            "type": "revolute",
            "upper": 1.5708
        },
        {
            "axis": [
                0.0,
                0.0,
                1.0
            ],
            "lower": -3.14159,
            "name": "shoulderPanAngle",
            "type": "revolute",
            "upper": 3.14159
        }
    ]
}
