// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/qtros/examples/robotarmcollision/simple_arm.urdf' on 2026-09-18T11:29:23.470640





import QtQuick
import QtQuick3D
import QtQuick3D.Helpers
import QtQuick3D.Physics

Node {
    id: rootNode

    required property SimpleArmControl control
    property real sceneUnitsPerMeter: 100.0
    property real instanceScale: 1.0
    scale: Qt.vector3d(instanceScale, instanceScale, instanceScale)

    function toEulerAngle(radians) { return radians * (180 / Math.PI) }

    // Orientation of the floating base (the root link), applied in *scene* space.
    // Bind to a body-pose / odometry source via the bridge, e.g.
    // poseSubscriber.pose.orientation.toQuaternion() (a QtQuick3D-frame quaternion).
    // Identity by default, so a fixed-base robot (arm on a bench, mill) can ignore
    // it. Articulation is driven separately by joint_states; this is the one
    // transform a joint can't provide.
    property quaternion baseOrientation: Qt.quaternion(1, 0, 0, 0)

    readonly property alias baseLinkPosition: base_link.scenePosition
    readonly property alias upperArmLinkPosition: upper_arm_link.scenePosition
    readonly property alias forearmLinkPosition: forearm_link.scenePosition
    readonly property alias wristLinkPosition: wrist_link.scenePosition

    // baseOrientation (scene space) ∘ Convert-to-Y-up (R_conv): apply the body
    // orientation outside the Z-up→Y-up geometry conversion, so a pitch reads as
    // a pitch (R_conv ∘ baseOrientation would act in Z-up and pitch-as-roll).
    rotation: baseOrientation.times(Qt.quaternion(0.50000000, -0.50000000, -0.50000000, -0.50000000))

    Node {
        DynamicRigidBody {
            id: base_linkPhysics
            isKinematic: rootNode.control ? rootNode.control.isKinematic : true
            sendTriggerReports: rootNode.control ? rootNode.control.sendTriggerReports : false
            collisionShapes: [
                ConvexMeshShape {
                    source: "Generated/QtQuick3D/BaseLinkCollision/meshes/node.mesh"
                    scale: Qt.vector3d(100.0, 100.0, 100.0)
                    position: Qt.vector3d(0.0, 0.0, 0.05)
                }
            ]
            Model {
                id: base_link
                position: Qt.vector3d(0.0, 0.0, 5.0)
                source: "#Cube"
                scale: Qt.vector3d(0.15, 0.15, 0.1)
                materials: [ PrincipledMaterial { baseColor: Qt.rgba(0.550000, 0.550000, 0.550000, 1.000000) } ]
            }
            Node {
                id: shoulder_pan
                position: Qt.vector3d(0.0, 0.0, 10.0)
                Node {
                    id: shoulder_panPivot
                    readonly property vector3d axis: Qt.vector3d(0.0, 0.0, 1.0)
                    rotation: Quaternion.fromAxisAndAngle(axis, rootNode.toEulerAngle(rootNode.control.shoulderPanAngle))
                    DynamicRigidBody {
                        id: upper_arm_linkPhysics
                        isKinematic: rootNode.control ? rootNode.control.isKinematic : true
                        sendTriggerReports: rootNode.control ? rootNode.control.sendTriggerReports : false
                        mass: 1.0
                        massMode: DynamicRigidBody.MassAndInertiaMatrix
                        // inertia matrix: [ixx, ixy, ixz, iyx, iyy, iyz, izx, izy, izz]
                        inertiaMatrix: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
                        collisionShapes: [
                            ConvexMeshShape {
                                source: "Generated/QtQuick3D/UpperArmLinkCollision/meshes/node.mesh"
                                scale: Qt.vector3d(100.0, 100.0, 100.0)
                                position: Qt.vector3d(0.0, 0.0, 0.14)
                            }
                        ]
                        Model {
                            id: upper_arm_link
                            position: Qt.vector3d(0.0, 0.0, 14.0)
                            source: "#Cube"
                            scale: Qt.vector3d(0.08, 0.08, 0.28)
                            materials: [ PrincipledMaterial { baseColor: Qt.rgba(0.200000, 0.400000, 0.800000, 1.000000) } ]
                        }
                        Node {
                            id: shoulder_lift
                            position: Qt.vector3d(0.0, 0.0, 28.0)
                            Node {
                                id: shoulder_liftPivot
                                readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                                rotation: Quaternion.fromAxisAndAngle(axis, rootNode.toEulerAngle(rootNode.control.shoulderLiftAngle))
                                DynamicRigidBody {
                                    id: forearm_linkPhysics
                                    isKinematic: rootNode.control ? rootNode.control.isKinematic : true
                                    sendTriggerReports: rootNode.control ? rootNode.control.sendTriggerReports : false
                                    mass: 0.8
                                    massMode: DynamicRigidBody.MassAndInertiaMatrix
                                    // inertia matrix: [ixx, ixy, ixz, iyx, iyy, iyz, izx, izy, izz]
                                    inertiaMatrix: [0.005, 0.0, 0.0, 0.0, 0.005, 0.0, 0.0, 0.0, 0.005]
                                    collisionShapes: [
                                        ConvexMeshShape {
                                            source: "Generated/QtQuick3D/ForearmLinkCollision/meshes/node.mesh"
                                            scale: Qt.vector3d(100.0, 100.0, 100.0)
                                            position: Qt.vector3d(0.0, 0.0, 0.12)
                                        }
                                    ]
                                    Model {
                                        id: forearm_link
                                        position: Qt.vector3d(0.0, 0.0, 12.0)
                                        source: "#Cube"
                                        scale: Qt.vector3d(0.07, 0.07, 0.24)
                                        materials: [ PrincipledMaterial { baseColor: Qt.rgba(0.200000, 0.700000, 0.300000, 1.000000) } ]
                                    }
                                    Node {
                                        id: elbow_flex
                                        position: Qt.vector3d(0.0, 0.0, 24.0)
                                        Node {
                                            id: elbow_flexPivot
                                            readonly property vector3d axis: Qt.vector3d(0.0, 1.0, 0.0)
                                            rotation: Quaternion.fromAxisAndAngle(axis, rootNode.toEulerAngle(rootNode.control.elbowFlexAngle))
                                            DynamicRigidBody {
                                                id: wrist_linkPhysics
                                                isKinematic: rootNode.control ? rootNode.control.isKinematic : true
                                                sendTriggerReports: rootNode.control ? rootNode.control.sendTriggerReports : false
                                                mass: 0.3
                                                massMode: DynamicRigidBody.MassAndInertiaMatrix
                                                // inertia matrix: [ixx, ixy, ixz, iyx, iyy, iyz, izx, izy, izz]
                                                inertiaMatrix: [0.001, 0.0, 0.0, 0.0, 0.001, 0.0, 0.0, 0.0, 0.001]
                                                collisionShapes: [
                                                    ConvexMeshShape {
                                                        source: "Generated/QtQuick3D/WristLinkCollision/meshes/node.mesh"
                                                        scale: Qt.vector3d(100.0, 100.0, 100.0)
                                                    }
                                                ]
                                                Model {
                                                    id: wrist_link
                                                    source: "#Sphere"
                                                    scale: Qt.vector3d(0.08, 0.08, 0.08)
                                                    materials: [ PrincipledMaterial { baseColor: Qt.rgba(0.900000, 0.500000, 0.100000, 1.000000) } ]
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
