@startuml
QEventLoop -> QWSI : sendWindowSystemEvents
activate QGuiApp
QWSI -> QGuiApp : processWindowSystemEvent
note right: QWindowSystemInterfacePrivate::MouseEvent comes in
participant "QEventPoint" as activePoint << activePoint >>
QGuiApp -> QPointingDevice : activePoint(0)
QPointingDevice --> QGuiApp : activePoint
activate QMouseEvent
QGuiApp -> QMouseEvent : ctor
activate QEventPoint
QMouseEvent -> QEventPoint : ctor
QGuiApp -> activePoint : updateFrom(QEventPoint)
group Pointer Event Delivery
QGuiApp -> QGuiApp : processMouseEvent
QGuiApp -> QGuiApp : notify
QGuiApp -> QQWindow : event
QQWindow -> QQWindow : mousePressEvent
QQWindow -> QQWindow : deliverPressOrReleaseEvent
QQWindow -> QQWindow : pointerTargets (recursive)
QQWindow -> Item : anyPointerHandlerWants
Item -> DragHandler : wantsEventPoint
QQWindow -> QQWindow : deliverMatchingPointsToItem
QQWindow -> Item : handlePointerEvent
Item -> DragHandler : handlePointerEvent
DragHandler -> DragHandler : wantsPointerEvent
DragHandler -> DragHandler : handlePointerEventImpl
DragHandler -> QEventPoint : setGrabberPointerHandler
DragHandler -> QEventPoint : setAccepted
end
QGuiApp -> activePoint : copyGrabbersFrom(QEventPoint)
return
deactivate QGuiApp
destroy QMouseEvent
destroy QEventPoint
@enduml
