@startuml
participant "QPointingDevice"
participant "QPointingDevPriv_EventPointData"
activate QGuiApp
note right: QWindowSystemInterfacePrivate::MouseEvent comes in
QGuiApp -> QGuiApp : processMouseEvent
participant "QEventPoint"
activate QEventPoint
activate QMouseEvent
QGuiApp -> QMouseEvent : ctor
QGuiApp -> QGuiApp : processMouseEvent
group Event Delivery in Window's DeliveryAgent
QGuiApp -> QQWindow : event
QQWindow -> QQDeliveryAgent : event
QQDeliveryAgent -> QQDeliveryAgent : ...
QQDeliveryAgent -> QQ3DViewport : event
activate QQ3DViewport
QQ3DViewport -> QQ3DViewport : internalPick
note right: hit-test the 3D Model hit; find the 2D subscene's root Item
QQ3DViewport -> QQ3DDefaultMaterial : diffuseMap()->sourceItem()
QQ3DViewport -> TapHandler : handlePointerEvent
note right: TapHandler on a 3D Model
group Subscene Event Delivery
activate subscene_QQDeliveryAgent
QQ3DViewport -> subscene_QQDeliveryAgent : event
subscene_QQDeliveryAgent -> Item : anyPointerHandlerWants
Item -> DragHandler : wantsEventPoint
subscene_QQDeliveryAgent -> subscene_QQDeliveryAgent : deliverMatchingPointsToItem
subscene_QQDeliveryAgent -> Item : handlePointerEvent
note right: handlers go first
Item -> DragHandler : handlePointerEvent
DragHandler -> QMouseEvent : addPassiveGrabber
QMouseEvent -> QPointingDevice : addPassiveGrabber
QPointingDevice -> subscene_QQDeliveryAgent : onGrabChanged
DragHandler -> DragHandler : grabChanged
QGuiApp -> Item : event
note right: then the item itself
Item -> Item : mousePressEvent
subscene_QQDeliveryAgent -> QMouseEvent : setExclusiveGrabber
note right: if Item subclass allows the event to remain accepted
QMouseEvent -> QPointingDevice : setExclusiveGrabber
QPointingDevice -> QPointingDevPriv_EventPointData : exclusiveGrabber = item
QPointingDevice -> QPointingDevice : grabChanged
QPointingDevice -> subscene_QQDeliveryAgent : onGrabChanged
subscene_QQDeliveryAgent -> QPointingDevPriv_EventPointData : exclusiveGrabberContext = agent
note left: remember that the\nsubscene agent\nhandles this grab
deactivate subscene_QQDeliveryAgent
deactivate QQ3DViewport
end
end
deactivate QGuiApp
destroy QMouseEvent
destroy QEventPoint
@enduml
